### ISSUE TITLE
NickServ login

### ISSUE THREAD

**Issue by kinduff** [flavorjones/irc-notification-resource#6]
Is there a way to send a message before joining a channel and be able to login to NickServ?

**Comment by flavorjones** [comment]
@kinduff sorry for my slow reply; just saw this now.

I'm not sure what you're asking. Can you help me understand what you're trying to do, maybe by asking it in a different way?

**Comment by kinduff** [comment]
Sure, sorry about that.

I need to login to a server but it requires NickServ authentication before joining a channel. So I'm looking for something like this:
1. Connect to server
2. Send auth details for NickServ (a regular message works)
3. Join channel

**Comment by flavorjones** [comment]
Oh, sure -- see #4 for progress on that! I'm going to close this issue and we can continue the conversation there.

**Comment by flavorjones** [comment]
Try the latest on DockerHub and let me know how it goes! Check out the README for guidance on joining the channel (which is not default behavior).
